"""create events table

Revision ID: 1b9365548a60
Revises: ffa08d595bb7
Create Date: 2026-07-14 18:18:56.537459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9365548a60'
down_revision: Union[str, Sequence[str], None] = 'ffa08d595bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('known_face_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('KNOWN_FACE', 'UNKNOWN_FACE', 'CAMERA_STARTED', 'CAMERA_STOPPED', 'CAMERA_OFFLINE', name='eventtype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['known_face_id'], ['known_faces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
